"""eliminada el campo year

Revision ID: a2212016ece6
Revises: 30b85e9a07f8
Create Date: 2024-11-20 16:14:38.345624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                    


# revision identifiers, used by Alembic.
revision: str = 'a2212016ece6'
down_revision: Union[str, None] = '30b85e9a07f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
