services:

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  web:
    build: ./project
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}

  